-- Drop and recreate Users table (Example)
DROP TABLE IF EXISTS widgets CASCADE;

DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS orders CASCADE;

DROP TABLE IF EXISTS dishes CASCADE;

DROP TABLE IF EXISTS payment_methods CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  is_admin BOOLEAN NOT NULL DEFAULT FALSE,
  phone VARCHAR(255) NOT NULL
);

CREATE TABLE dishes (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  price INTEGER NOT NULL,
  has_nuts BOOLEAN NOT NULL DEFAULT FALSE,
  is_vegan BOOLEAN NOT NULL DEFAULT FALSE,
  is_vegetarian BOOLEAN NOT NULL DEFAULT FALSE,
  thumbnail_photo VARCHAR(255) NOT NULL,
  quantity SMALLINT NOT NULL DEFAULT 1
);

CREATE TABLE payment_methods (
  id SERIAL PRIMARY KEY NOT NULL,
  credit BOOLEAN NOT NULL DEFAULT FALSE,
  cash BOOLEAN NOT NULL DEFAULT FALSE,
  apple BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE orders (
  id SERIAL PRIMARY KEY NOT NULL,
  timestamp TIMESTAMP NOT NULL,
  is_ready BOOLEAN NOT NULL DEFAULT FALSE,
  total_price INTEGER NOT NULL,
  taxes INTEGER NOT NULL,
  tip INTEGER,
  notes TEXT,
  approx_time INTEGER NOT NULL,
  dish_id INTEGER REFERENCES dishes(id) ON DELETE CASCADE,
  method_id INTEGER REFERENCES payment_methods(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);
